# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{livedate}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Erik Hansson"]
  s.date = %q{2009-09-17}
  s.description = %q{= Livedate

A simple Rack middleware that parses a dates using Chronic, and 
returns the result in a standardized manner. The idea is to use 
this to verify the input in date input fields using AJAX, to 
provide immediate feedback to the user.


== Usage

Include Livedate in your middleware stack. In Rails, this
is done in environment.rb

  config.gem 'livedate'
  config.middleware.use "Livedate"

Specify the desired date + datetime formats you want too. Default
error message for strings that Chronic can't pass can also 
be provided. The defaults are:

  config.middleware.use "Livedate", 
    :date_format => '%Y-%m-%d',
    :datetime_format => ''%Y-%m-%d %H:%M',
    :invalid_format => ''

This will catch requests to /parsedate. Use GET requests and
provide a parameter 'date' or 'datetime'. The value will be 
parsed by Chronic and returned formatted as 2009-01-01 or
2009-01-01 12:45, depending on the parameter name.


== Scripts

There are two generators available to get simple javascripts 
that use livedate. Both will replace the contents on input
elements with classes .date or .datetime on change with the
result from the Chronic parse.

  script/generate livedate_jquery
  script/generate livedate_prototype
  
Will put the appropriate version of the script in your
public/javascripts directory. Feel free to change these
if you need a different behavior.
}
  s.email = %q{erik@bits2life.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "VERSION",
     "generators/livedate_jquery_generator.rb",
     "generators/livedate_prototype_generator.rb",
     "generators/templates/javascript/jquery.js",
     "generators/templates/javascript/prototype.js",
     "lib/livedate.rb"
  ]
  s.homepage = %q{http://www.erikhansson.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.8")
  s.requirements = ["chronic"]
  s.rubyforge_project = %q{livedate}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A simple Rack-middleware for parsing dates with Chronic}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chronic>, [">= 0.2.3"])
    else
      s.add_dependency(%q<chronic>, [">= 0.2.3"])
    end
  else
    s.add_dependency(%q<chronic>, [">= 0.2.3"])
  end
end
